import * as fs from 'fs';
import * as path from 'path';

export interface ProvisionedProjectEnv {
  wmProjectId: string;
  studioProjectId: string;
  projectName: string;
  appName: string;
  appPackage: string;
  rnProjectFolder: string;
}

/** Random Studio-safe project name (no user input required). */
export function generateStudioProjectName(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  const raw = `CliAuto${ts}${rand}`.replace(/[^a-zA-Z0-9]/g, '');
  return raw.slice(0, 28) || `CliAuto${Date.now()}`;
}

export function deriveAppPackage(projectName: string): string {
  const slug = projectName.toLowerCase().replace(/[^a-z0-9]/g, '') || 'cliauto';
  return `com.wavemaker.${slug}`;
}

export function deriveRnProjectFolder(appName: string): string {
  return `${appName}-native-mobile_0.0.1`;
}

export function isNewProjectMode(): boolean {
  return (process.env.PROJECT_MODE || 'Existing Project').trim() === 'New Project';
}

/**
 * When PROJECT_MODE=New Project, map CLI provisioned project + WM credentials
 * onto SECURITY_* so security scan uses the same newly created project.
 */
export function applyProvisionedProjectToSecurityEnv(): void {
  if (!isNewProjectMode()) return;

  const wmProjectId =
    process.env.WM_PROJECT_ID?.trim() || process.env.PROJECT_ID?.trim();
  const studioProjectId = process.env.STUDIO_PROJECT_ID?.trim();

  if (wmProjectId) process.env.SECURITY_PROJECT_ID = wmProjectId;
  if (studioProjectId) process.env.SECURITY_STUDIO_PROJECT_ID = studioProjectId;

  const username =
    process.env.WM_USERNAME?.trim() ||
    process.env.WMO_USER?.trim() ||
    process.env.STUDIO_USERNAME?.trim();
  const password =
    process.env.WM_PASSWORD?.trim() ||
    process.env.WMO_PASS?.trim() ||
    process.env.STUDIO_PASSWORD?.trim();
  if (username) process.env.SECURITY_USERNAME = username;
  if (password) process.env.SECURITY_PASSWORD = password;

  const studioUrl =
    process.env.STUDIO_URL?.trim() || process.env.STUDIO_BASE_URL?.trim();
  if (studioUrl) process.env.SECURITY_STUDIO_URL = studioUrl;

  if (process.env.APP_NAME?.trim()) {
    process.env.SECURITY_APP_NAME = process.env.APP_NAME.trim();
  }
  if (process.env.APP_PACKAGE?.trim()) {
    process.env.SECURITY_APP_PACKAGE = process.env.APP_PACKAGE.trim();
  }
  if (process.env.RN_PROJECT_FOLDER?.trim()) {
    process.env.SECURITY_RN_PROJECT_FOLDER = process.env.RN_PROJECT_FOLDER.trim();
  }
}

export function writeCiProjectEnvFile(
  targetPath: string,
  project: ProvisionedProjectEnv
): void {
  const lines = [
    '# Generated by scripts/provision-studio-project.ts — do not commit',
    `export WM_PROJECT_ID="${project.wmProjectId}"`,
    `export PROJECT_ID="${project.wmProjectId}"`,
    `export STUDIO_PROJECT_ID="${project.studioProjectId}"`,
    `export APP_NAME="${project.appName}"`,
    `export APP_PACKAGE="${project.appPackage}"`,
    `export RN_PROJECT_FOLDER="${project.rnProjectFolder}"`,
    // PRISM NATIVE_MOBILE defaults for freshly created projects
    `export APP_VERIFICATION_ID="~mobile_navbar1_title"`,
    `export WEB_PREVIEW_XPATH="//*[contains(@class,'app-page') or @data-role='page-content']"`,
    '',
  ];
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, lines.join('\n'), 'utf-8');
}
